---
title: "SCORE: Kim & Radoias (2016) reproduction"
subtitle: "Data coordination"
author: "Radek Panczak"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
  code_folding: show
self_contained: true
highlight: pygments
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs") })
---

<!-- ----------------------------------------------------- -->

```{r setup, include = FALSE}
set.seed(12345)
options(scipen = 999)
options(max.print = "75")
library(pacman)
p_load(osfr, readr, dplyr)
```

```{r knit-setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(cache = FALSE,
                      prompt = FALSE,
                      tidy = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE)
knitr::opts_knit$set(width = 125)
mu <- Hmisc::markupSpecs$html
```

<!-- ------------------------------------------------------------ --> 

Automating data and code upload to OSF.  

# Location

```{r osf-auth, include=FALSE}
osf_pat <- readr::read_file("osf_pat.txt")
osf_auth(osf_pat)

project <- osf_retrieve_node("7msd8")

project

project %>%
  osf_ls_nodes()
```

# Data

```{r osf-up, eval=FALSE, include=FALSE}
upload_location <- project %>%
  osf_ls_nodes() %>%
  filter(name == "Data")

upload_location

osf_upload(upload_location, 
           path = "data-raw", 
           recurse = TRUE,
           progress = TRUE,
           conflicts = "overwrite")
```

# Analysis

```{r osf-up, eval=FALSE, include=FALSE}
upload_location <- project %>%
  osf_ls_nodes() %>%
  filter(name == "Analysis")

# Rmd
osf_upload(upload_location, 
           path = "analyses", 
           conflicts = "overwrite")
# html
osf_upload(upload_location, 
           path = "docs", 
           conflicts = "overwrite")
```